#! /bin/bash

# find current repo path
export REPO=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
export RUSTUP_HOME=$REPO/bin
export CARGO_HOME=$REPO/bin

deactivate () {
    unset RUSTUP_HOME
    unset CARGO_HOME
    unset REPO
    if [ -n "${_OLD_VIRTUAL_PS1:-}" ] ; then
        PS1="${_OLD_VIRTUAL_PS1:-}"
        export PS1
        unset _OLD_VIRTUAL_PS1
    fi

    unset -f deactivate
}

source $REPO/bin/env

# preserve old prompt
_OLD_VIRTUAL_PS1="${PS1:-}"
export PS1="(rust) ${PS1:-}"
export RUST_TEST_THREADS=1
